#This script has only been tested on OpenSuSE SLES 15.
#This script will isntall HBA drivers located at specific FTP server / directory.
#Author - Parker Schoenig
#Parker.Schoenig@dell.com

import paramiko
import socket
import getpass
import time

print('This script will download HBA drivers and managers')

time.sleep(1)
print('Select HBA Brand')
print('1. Emulex')
print('2. QLogic')
reqInput1 = input('Enter correlating #: ')
print('Select host OS')
print('1. SLES 11')
print('2. SLES 12')
print('3. SLES 15')
print('4. RHEL 7.6-7.7')
print('5. RHEL 8')
reqInput2 = input('Enter correlating #: ')
host = input('Enter IP: ')
username = input('login as: ')
password = getpass.getpass(username + '@' + host + '\x27s password: ')
print("")
print('Checking network on ' + host)
time.sleep(2)
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
result = sock.connect_ex((host, 22))
if result == 0:
    print(host + ' is alive, establishing connection')
#SLES11 - Emulex
    if reqInput1 == '1':
        if reqInput2 == '1':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#SLES12 - Emulex
    if reqInput1 == '1':
        if reqInput2 == '2':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#SLES15 - Emulex
    if reqInput1 == '1':
        if reqInput2 == '3':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#RHEL7.6-7.7 - Emulex
    if reqInput1 == '1':
        if reqInput2 == '4':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#RHEL8 - Emulex
    if reqInput1 == '1':
        if reqInput2 == '5':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#SLES11 - QLogic
    if reqInput1 == '2':
        if reqInput2 == '1':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#SLES12 - QLogic
    if reqInput1 == '2':
        if reqInput2 == '2':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#SLES15 - QLogic
    if reqInput1 == '2':
        if reqInput2 == '3':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#RHEL7.6-7.7 - QLogic
    if reqInput1 == '2':
        if reqInput2 == '4':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)
#RHEL8 - QLogic
    if reqInput1 == '2':
        if reqInput2 == '5':
            try:
                p = paramiko.SSHClient()
                p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                p.connect(host, username=username, password=password)
                channel = p.invoke_shell()
                print('Connected to ' + host)
                time.sleep(2)
                print("Creating /kits directory...")
                channel.send('cd /')
                time.sleep(1)
                channel.send('mkdir kits\n')
                print("Downloading drivers and driver manager...")
                time.sleep(1)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('yes\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                channel.send('scp -r root@<enter ftp ip and path>/kits\n')
                time.sleep(2)
                channel.send('dangerous\n')
                time.sleep(2)
                p.close()
            except paramiko.AuthenticationException:
                print('Wrong credentials for ' + host)
                print('Could not change suffixes')
                print('Closing application in 10 seconds, please wait')
                time.sleep(10)

else:
    print('Unable to connect to ' + host + '. Please check network.')
    print('Closing application in 10 seconds, please wait')
    time.sleep(10)


print('Files can be found in /kits. Exiting in 5 seconds, please wait')
time.sleep(5)
